# Generated by Django 3.0.3 on 2020-02-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_lots', models.IntegerField(default=0)),
                ('private', models.BooleanField(default=False)),
                ('club_house', models.BooleanField(default=False)),
                ('amenites', models.BooleanField(default=False)),
                ('park', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
