# Generated by Django 3.0.3 on 2020-02-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdivisions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
