from django.db import models
from subdivisions.models import Subdivision

class Lot(models.Model):
    subdivision_id = models.ForeignKey(Subdivision, on_delete=models.CASCADE)
    lot_number = models.IntegerField(null=True, blank=True)
    lot_type = models.CharField(max_length=50, null=True, blank=True)
    block_number = models.IntegerField(null=True, blank=True)
    square_meters = models.IntegerField(null=True, blank=True)
    front_meters = models.IntegerField(null=True, blank=True)
    construction_meters = models.IntegerField(null=True, blank=True)
    extra_meters = models.IntegerField(null=True, blank=True)
    base_price = models.IntegerField(null=True, blank=True)
    prototype = models.IntegerField(null=True, blank=True)
    facade = models.CharField(max_length= 250, null=True, blank=True)
    levels = models.IntegerField(null=True, blank=True)
    bedrooms = models.IntegerField(null=True, blank=True)
    full_bathrooms = models.IntegerField(null=True, blank=True)
    half_bathrooms = models.IntegerField(null=True, blank=True)
    warehouses = models.IntegerField(null=True, blank=True)
    service_room = models.BooleanField(null=True)
    furnished = models.BooleanField(null=True)
    minisplit = models.BooleanField(null=True)
    air_condition = models.BooleanField(null=True)
    alarm = models.BooleanField(null=True)
    doors = models.BooleanField(null=True)
    closets = models.BooleanField(null=True)
    laundry = models.BooleanField(null=True)
    garage_space = models.IntegerField(null=True, blank=True)
    backyard = models.BooleanField(null=True)
    gardening = models.BooleanField(null=True)
    private_pool = models.BooleanField(null=True)
    bbq_area = models.BooleanField(null=True)
    kitchen = models.BooleanField(null=True)
    frontdoor_security = models.BooleanField(null=True)
    backdoor_security = models.BooleanField(null=True)
    windows_protectors = models.BooleanField(null=True)
    canceleria = models.BooleanField(null=True)
    cctv = models.BooleanField(null=True)
    automation = models.BooleanField(null=True)
    water_tank = models.BooleanField(null=True)
    description = models.TextField(blank=True)
    notes = models.TextField(blank=True)
 
    class Meta:
        unique_together = ('subdivision_id', 'lot_number',)