# Generated by Django 3.0.3 on 2020-02-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200208_2056'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('lot_id',), name='unique_sold_lot'),
        ),
    ]
