# Generated by Django 3.0.3 on 2020-02-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('name', 'email')},
        ),
    ]
