# Generated by Django 3.0.3 on 2020-02-09 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subdivisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_type', models.CharField(blank=True, max_length=50, null=True)),
                ('lot_number', models.IntegerField(blank=True, null=True)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('square_meters', models.IntegerField(blank=True, null=True)),
                ('front_meters', models.IntegerField(blank=True, null=True)),
                ('construction_meters', models.IntegerField(blank=True, null=True)),
                ('extra_meters', models.IntegerField(blank=True, null=True)),
                ('base_price', models.IntegerField(blank=True, null=True)),
                ('prototype', models.IntegerField(blank=True, null=True)),
                ('facade', models.CharField(blank=True, max_length=250, null=True)),
                ('levels', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('full_bathrooms', models.IntegerField(blank=True, null=True)),
                ('half_bathrooms', models.IntegerField(blank=True, null=True)),
                ('warehouses', models.IntegerField(blank=True, null=True)),
                ('service_room', models.BooleanField(null=True)),
                ('furnished', models.BooleanField(null=True)),
                ('minisplit', models.BooleanField(null=True)),
                ('air_condition', models.BooleanField(null=True)),
                ('alarm', models.BooleanField(null=True)),
                ('doors', models.BooleanField(null=True)),
                ('closets', models.BooleanField(null=True)),
                ('laundry', models.BooleanField(null=True)),
                ('garage_space', models.IntegerField(blank=True, null=True)),
                ('backyard', models.BooleanField(null=True)),
                ('gardening', models.BooleanField(null=True)),
                ('private_pool', models.BooleanField(null=True)),
                ('bbq_area', models.BooleanField(null=True)),
                ('kitchen', models.BooleanField(null=True)),
                ('frontdoor_security', models.BooleanField(null=True)),
                ('backdoor_security', models.BooleanField(null=True)),
                ('windows_protectors', models.BooleanField(null=True)),
                ('canceleria', models.BooleanField(null=True)),
                ('cctv', models.BooleanField(null=True)),
                ('automation', models.BooleanField(null=True)),
                ('water_tank', models.BooleanField(null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('subdivision_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivisions.Subdivision')),
            ],
        ),
    ]
