# Generated by Django 3.0.3 on 2020-02-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdivisions', '0002_auto_20200208_2220'),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('subdivision_id', 'lot_number')},
        ),
    ]
